# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ypfPsOcyFQBAv4da1MjQRNC7qIiIo-51
"""

import pandas as pd

datos = {
    "ID": [1, 2, 3, 4, 5, 6],
    "Nombre": [
        "Ana",
        "Carlos",
        "Maria",
        "Jose",
        "Laura",
        "Pedro"
    ],
    "Edad": [20, 22, 19, 25, 21, 23],
    "Curso": [
        "Python",
        "Python",
        "SQL",
        "SQL",
        "Python",
        "SQL"
    ],
    "Nota": [95, 78, 88, 65, 92, 55],
    "Asistencia": [90, 85, 95, 70, 98, 60]
}
animales = {
    "Perro": "Mamífero",
    "Gato": "Mamífero",
    "Conejo": "Mamífero",
    "Caballo": "Mamífero",
    "Vaca": "Mamífero",
    "Gallina": "Ave",
    "Pato": "Ave",
    "Águila": "Ave",
    "Tortuga": "Reptil",
    "Cocodrilo": "Reptil",
    "Rana": "Anfibio",
    "Salmón": "Pez",
    "Tiburón": "Pez",
    "Pulpo": "Molusco",
    "Mariposa": "Insecto"
}

df = pd.DataFrame(datos)
df_animales = pd.DataFrame(
    list(animales.items()),
    columns=["Animal", "Tipo"]
)
while True:
  print("\n=== Menu ===")
  print("1- saludar")
  print("2- mostrar nombre")
  print("3- sumar numero")
  print("4- mostrar promedio")
  print("5- aplicar analisis")
  print("6- buscar animal")
  print("7\n- salir")
  opcion = input("seleccione una opcion")

  if opcion == "1":
    print("hola")
  elif opcion == "2":
    nombre = input("digite su nombre: ")
    print("hola",nombre)

  elif opcion == "3":
    numero1 = float(input("digite el numero 1: "))
    numero2 = float(input("digite el numero 2: "))
    print("la suma es: ",numero1+numero2)

  elif opcion == "4":
    numero1 = float(input("digite la nota 1: "))
    numero2 = float(input("digite la nota 2: "))
    promedio = numero1 / numero2
    print("el promedio es: ",promedio)

  elif opcion == "5":
    #menu analisis
    print("\n=== Menu ===")
    print("1- mostrar tabla")
    print("2- mostrar informacion")
    print("3- mostrar estadistica")
    print("4- buscar estudiante")
    print("5- mostrar estudiantes aprobados")
    print("6- mostrar estudiantes reprobados")
    print("7- mostrar promedio de notas")
    print("8- mostrar promedio por curso")
    print("9- profesor")
    print("10- salir")
    opcion = input("seleccione una opcion")
    print("analizando")
    while True:
      if opcion == "1":
         #Mostrar tabla
         print(df) #muestra la tabla (dataframe)

      elif opcion == "2":
        #mostrar informacion
        print(df.info()) #muestra la informacion del dataframe

      elif opcion == "3":
         #mostrar estadistica
         print(df.describe()) #muestra la estadistica del dataframe

      elif opcion == "4":
        #buscar estudiante
        nombre = input("digite el nombre del estudiante: ")
        print(df[df["Nombre"] == nombre]) #muestra el estudiante
        # print() -> Muestra el resultado en la consola.
        # df["Nombre"] -> Selecciona la columna "Nombre" del DataFrame.
        # == nombre -> Compara cada valor de la columna con el nombre ingresado por el usuario.
        # df[...] -> Filtra el DataFrame y conserva únicamente las filas donde la comparación es True.

        if estudiante.empty:
          print("Estudiante no encontrado.")
        else:
          print(estudiante)

      elif opcion == "5":
        #mostrar estudiantes aprobados
        print(df[df["Nota"] >= 70])
        #df[df["Nota"] >= 70] -> Filtra el DataFrame para mostrar solo las filas donde la columna "Nota" es mayor o igual a 70.

      elif opcion == "6":
        print(df[df["Nota"] < 70])
        #mostrar estudiantes reprobados

      elif opcion== "7":
       #promedio de notas
       print(df["Nota"].mean())
       #df["Nota"].mean() -> Calcula el promedio de la columna "Nota" del DataFrame.

      elif opcion == "8":
      #promedio curso
        curso = input("digite el curso: ")
        print(df[df["Curso"] == curso]["Nota"].mean())

      elif opcioon == "9":
        print("profesor")

      elif opcion == "10":
        print("\n buscando profesor...")
        print("Prof. Bernan")
        break
      else: print("opcion invalida")
      break


  elif opcion == "6":
    print("Buscando el animal")
    animal = input("Digite el animal: ").capitalize()

    if animal in animales:
        print(f"\n{animal} es un {animales[animal]}")

    else:
        print("Animal no encontrado.")

  elif opcion == "7":
    break
  else:
    print("opcion invalida")
#